/**
 * Builds the block appended to every agent's generated guidelines file.
 * Names the local canonical source directory as the place to edit.
 * Also names every remote source's own repository, when this project pulls shared content from one or more.
 */
export function guidelinesSuffix(options: GuidelinesSuffixOptions): string {
    const { remoteUrls } = options;

    const remoteLine =
        remoteUrls.length > 0
            ? ` This project also pulls shared guidelines, skills, commands, and MCP servers from ${listUrls(remoteUrls)}, edit the relevant repository instead for a change meant for every project pulling from it.`
            : "";

    return `
---

For AI agent reading this file, these guidelines, skills, and MCP servers were generated by \`agenteq\`. Do not edit this file directly. Your changes will be overwritten on the next sync.

If the user asks you to update these guidelines, skills, or MCP servers, edit the source files instead. They live in this project's canonical source directory (\`.ai\` by default, or the directory this project configures).${remoteLine} Then run \`npx agenteq sync\` to regenerate this file.
`;
}

/*
 * Internal.
 */

function listUrls(urls: string[]): string {
    return urls.length === 1 ? urls[0] : urls.join(", ");
}

/*
 * Interface & Types.
 */

interface GuidelinesSuffixOptions {
    remoteUrls: string[];
}
