/**
 * Appended to every agent's generated guidelines file.
 */
export const GUIDELINES_SUFFIX = `
---

For AI agent reading this file, these guidelines, skills, and MCP servers were generated by \`agenteq\`. Do not edit this file directly. Your changes will be overwritten on the next sync.

If the user asks you to update these guidelines, skills, or MCP servers, edit the source files instead. They live in this project's canonical directory (\`.ai\` by default, or the directory this project configures). Then run \`npx agenteq sync\` to regenerate this file.
`;
